import MainTemp from "./components/templates/main/page";
import { Loading } from "./components/organisms/loading/loading";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "QR Absensi",
  description: "Generated by create next app",
}

export default function Home() {
  return (
    <section>
      <Loading duration={500} />
      <MainTemp />
    </section>
  );
}
